const translations = {
    fa: {
        loading: "در حال بارگذاری...", retry: "🔄 تلاش دوباره", searchPlaceholder: "جستجوی کوین...", coinName: "نام کوین", usdtPrice: "قیمت (USDT)", tomanPrice: "قیمت (تومان)", noResults: "کوینی با نام", notFound: "یافت نشد", error: "⚠️ خطا در بروزرسانی قیمت‌ها", settingsTitle: "تنظیمات", viewFullChart: "مشاهده نمودار کامل", supportTab: "پشتیبانی", offlineMessage: "شما آفلاین هستید، قیمت‌ها نمی‌توانند به روز باشند", close: "بستن",
        coinDetails: { lastUpdated: 'آخرین بروزرسانی', liveChart: 'نمودار زنده', marketStats: 'آمار بازار', supplyInfo: 'اطلاعات عرضه', high24h: 'بیشترین قیمت ۲۴ساعت', low24h: 'کمترین قیمت ۲۴ساعت', volume24h: 'حجم معاملات ۲۴ساعت', marketCap: 'ارزش بازار', circulatingSupply: 'عرضه در گردش', totalSupply: 'عرضه کل', maxSupply: 'حداکثر عرضه', currentPrice: 'قیمت فعلی', loading: 'در حال بارگذاری...', error: 'خطا در دریافت اطلاعات', offlineMessage: "حالت آفلاین - نمایش آخرین داده‌های ذخیره شده", lastUpdatedText: { justNow: "هم اکنون", minutesAgo: "دقیقه پیش", hoursAgo: "ساعت پیش" } },
        coinNames: { bitcoin: "بیت‌کوین", ethereum: "اتریوم", binancecoin: "بایننس کوین", ripple: "ریپل", dogecoin: "دوج‌کوین", solana: "سولانا", cardano: "کاردانو", tron: "ترون", polkadot: "پولکادات", "matic-network": "پالیگان", stellar: "استلار", litecoin: "لایت‌کوین", uniswap: "یونی‌سواپ", monero: "مونرو", aave: "آوه", pepe: "پپه", usdt: "تتر", hyperliquid: "هایپرلیکوئید", sui: "سویی", whitebit: "وایت بیت", mantle: "منتل", ethena: "اتنا", okb: "اوکی بی", memecoin: "میم کوین", near: "نیر", bittensor: "بیت تنسور", aptos: "آپتوس", arbitrum: "آربیتروم", kaspa: "کاسپا", cosmos: "کازموس", algorand: "الگورند", vechain: "وی چین", bonk: "بونک", fasttoken: "فست توکن", sky: "اسکای", filecoin: "فایل کوین", optimism: "اپتیمیسم", celestia: "سلستیا", "render-token": "رندر", fartcoin: "فارت کوین" } as { [key: string]: string },
        binanceSymbols: { bitcoin: "BTCUSDT", ethereum: "ETHUSDT", binancecoin: "BNBUSDT", ripple: "XRPUSDT", dogecoin: "DOGEUSDT", solana: "SOLUSDT", cardano: "ADAUSDT", tron: "TRXUSDT", polkadot: "DOTUSDT", "matic-network": "MATICUSDT", stellar: "XLMUSDT", litecoin: "LTCUSDT", uniswap: "UNIUSDT", chainlink: "LINKUSDT", "bitcoin-cash": "BCHUSDT", monero: "XMRUSDT", "ethereum-classic": "ETCUSDT", tezos: "XTZUSDT", eos: "EOSUSDT", aave: "AAVEUSDT", compound: "COMPUSDT", synthetix: "SNXUSDT", "yearn-finance": "YFIUSDT", usdt: "USDTUSDT" } as { [key: string]: string },
        coinGeckoIds: { BTC: "bitcoin", ETH: "ethereum", BNB: "binancecoin", XRP: "ripple", DOGE: "dogecoin", SOL: "solana", ADA: "cardano", TRX: "tron", DOT: "polkadot", MATIC: "matic-network", LTC: "litecoin", XLM: "stellar", UNI: "uniswap", XMR: "monero", AAVE: "aave", PEPE: "pepe", USDT: "tether" } as { [key: string]: string },
        darkMode: "حالت تاریک", persianLanguage: "زبان فارسی",
    },

    en: {
        loading: "Loading...", retry: "🔄 Retry", searchPlaceholder: "Search for a coin...", coinName: "Coin Name", usdtPrice: "Price (USDT)", tomanPrice: "Price (Toman)", noResults: "No coin named", notFound: "found", error: "⚠️ Error updating prices", settingsTitle: "Settings", viewFullChart: "View Full Chart", supportTab: "Support", offlineMessage: "You are offline, price can't be up to date.", close: "Close",
        coinDetails: { currentPrice: 'Current Price', liveChart: 'Live Chart', marketStats: 'Market Statistics', supplyInfo: 'Supply Information', high24h: '24h High', low24h: '24h Low', volume24h: '24h Volume', marketCap: 'Market Cap', circulatingSupply: 'Circulating Supply', totalSupply: 'Total Supply', maxSupply: 'Max Supply', loading: 'Loading...', error: 'Error loading data', lastUpdated: 'Last updated', offlineMessage: "Offline - Showing last saved data", lastUpdatedText: { justNow: "Just now", minutesAgo: "minutes ago", hoursAgo: "hours ago" } }, coinNames: { bitcoin: "Bitcoin", ethereum: "Ethereum", binancecoin: "Binance Coin", ripple: "Ripple", dogecoin: "Dogecoin", solana: "Solana", cardano: "Cardano", tron: "Tron", polkadot: "Polkadot", "matic-network": "Polygon", stellar: "Stellar", litecoin: "Litecoin", uniswap: "Uniswap", monero: "Monero", aave: "Aave", pepe: "Pepe", usdt: "Tether", hyperliquid: "Hyperliquid", sui: "Sui", whitebit: "Whitebit", mantle: "Mantle", ethena: "Ethena", okb: "OKB", memecoin: "Memecoin", near: "Near", bittensor: "Bittensor", aptos: "Aptos", arbitrum: "Arbitrum", kaspa: "Kaspa", cosmos: "Cosmos", algorand: "Algorand", vechain: "Vechain", bonk: "Bonk", fasttoken: "Fasttoken", sky: "Sky", filecoin: "Filecoin", optimism: "Optimism", celestia: "Celestia", "render-token": "Render", fartcoin: "Fartcoin" } as { [key: string]: string },
        binanceSymbols: { bitcoin: "BTCUSDT", ethereum: "ETHUSDT", binancecoin: "BNBUSDT", ripple: "XRPUSDT", dogecoin: "DOGEUSDT", solana: "SOLUSDT", cardano: "ADAUSDT", tron: "TRXUSDT", polkadot: "DOTUSDT", "matic-network": "MATICUSDT", stellar: "XLMUSDT", litecoin: "LTCUSDT", uniswap: "UNIUSDT", chainlink: "LINKUSDT", "bitcoin-cash": "BCHUSDT", monero: "XMRUSDT", "ethereum-classic": "ETCUSDT", tezos: "XTZUSDT", eos: "EOSUSDT", aave: "AAVEUSDT", compound: "COMPUSDT", synthetix: "SNXUSDT", "yearn-finance": "YFIUSDT", usdt: "USDTUSDT" } as { [key: string]: string },
        coinGeckoIds: { BTC: "bitcoin", ETH: "ethereum", BNB: "binancecoin", XRP: "ripple", DOGE: "dogecoin", SOL: "solana", ADA: "cardano", TRX: "tron", DOT: "polkadot", MATIC: "matic-network", LTC: "litecoin", XLM: "stellar", UNI: "uniswap", XMR: "monero", AAVE: "aave", PEPE: "pepe", USDT: "tether" } as { [key: string]: string },
        darkMode: "Dark Mode", persianLanguage: "Persian Language",
    }
};

export default translations;